[30/Aug/2025 14:19:07] "GET /api/perfil/ HTTP/1.1" 200 769
[30/Aug/2025 14:19:21] "OPTIONS /api/monitorar/ HTTP/1.1" 200 0
Exception in thread Thread-5 (_readerthread):
Exception in thread Thread-6 (_readerthread):
Traceback (most recent call last):
  File "C:\Users\cydyq\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 1043, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "C:\Users\cydyq\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Traceback (most recent call last):
  File "C:\Users\cydyq\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 1615, in _readerthread
    buffer.append(fh.read())
                  ~~~~~~~^^
  File "<frozen codecs>", line 325, in decode
  File "C:\Users\cydyq\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 1043, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 167: invalid continuation byte
  File "C:\Users\cydyq\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cydyq\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 1615, in _readerthread
    buffer.append(fh.read())
                  ~~~~~~~^^
  File "<frozen codecs>", line 325, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 11457: invalid continuation byte
Erro inesperado: 'NoneType' object has no attribute 'splitlines'
Internal Server Error: /api/monitorar/
[30/Aug/2025 14:19:40] "POST /api/monitorar/ HTTP/1.1" 500 53
